apiVersion: apps/v1
kind: Deployment
metadata:
  name: sue33
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sue33
  template:
    metadata:
      labels:
        app: sue33
    spec:
      containers:
      - image: okteto.dev/ray:latest
        name: sue33
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "404ee6aa-a258-4c91-a4b4-080004fd110c"
        - name: Vless_Path
          value: "/vl555"
        - name: Vmess_UUID
          value: "404ee6aa-a258-4c91-a4b4-080004fd110c"
        - name: Vmess_Path
          value: "/vm666"
        - name: Share_Path
          value: "/v2link"
