apiVersion: v1
kind: Service
metadata:
  name: sue33
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "sue33"
    port: 8080
  selector:
    app: sue33
